### ISSUE TITLE
potential discrepancy in TSC membership rules

### ISSUE THREAD

**Issue by jlipps** [jquery-foundation/CB#2]
In https://github.com/jquery-foundation/CB/blob/master/Project-Lifecycle.md I see:

> No more than 1/4 of the TSC is affiliated with the same employer.

But in https://github.com/jquery-foundation/CB/blob/master/BasePolicies/TSC-WG-Charter.md I see:

> No more than 1/3 of the [TSC or WG] members may be affiliated with the same employer.

Which is it?

**Comment by kborchers** [comment]
Sorry that was caught by the initial review committee before and I forgot to update it. It should be 1/3 in both places. I'll fix it this evening. Thanks!
